package nl.rws.re.rules.dakkapel;
import nl.rws.re.facts.dakkapelx.Node;
import nl.rws.re.facts.dakkapelx.Vraag;
import nl.rws.re.facts.dakkapelx.Antwoord;

dialect  "mvel"

rule "Node 1 antwoord NEE voor node 2"
    when
        not(Node(id == 1))
        Node(id == 2,antwoord==Antwoord.NEE.getValue())
    then
        insert(new Node(1,Antwoord.NEE.getValue()));
end
rule "Node 1 antwoord NEE voor node 3"
    when
        not(Node(id == 1))
        Node(id == 3,antwoord==Antwoord.NEE.getValue())
    then
        insert(new Node(1,Antwoord.NEE.getValue()));
end
rule "Node 1 antwoord JA"
    when
        Node(id == 2,antwoord==Antwoord.JA.getValue())
		Node(id == 3,antwoord==Antwoord.JA.getValue())

    then
        insert(new Node(1,Antwoord.JA.getValue()));
end
rule "vraag voor node 2"
    when
        not(Node(id == 2))
    then
        Vraag vraag = new Vraag();
        vraag.setVraagId("1");
        vraag.setConversionId(null);
        insert(vraag);
end
rule "vraag voor node 3"
    when
        not(Node(id == 3))
    then
        Vraag vraag = new Vraag();
        vraag.setVraagId("2");
        vraag.setConversionId(null);
        insert(vraag);
end
