package nl.rws.re.rules.dakkapel;
import nl.rws.re.facts.dakkapelx.Vraag;
import nl.rws.re.facts.dakkapelx.Antwoord;
import nl.rws.re.facts.dakkapelx.Node;

dialect  "mvel"

rule "vraag voor node 2"
    when
        not(Node(id == 2,antwoord==null))
    then
        Vraag vraag = new Vraag();
        vraag.setVraagId("1");
        insert(vraag);
end

rule "vraag voor node 3"
    when
        not(Node(id == 3,antwoord==null))
    then
        Vraag vraag = new Vraag();
        vraag.setVraagId("2");
        insert(vraag);
end

rule "Node 1 antwoord JA"
    when
        Node(id == 2,antwoord==Antwoord.JA.name())
        Node(id == 3,antwoord==Antwoord.JA.name())
    then
        insert(Antwoord.JA.name());
end

rule "Node 1 antwoord NEE voor node 2"
    when
        Node(id == 2,antwoord==Antwoord.NEE.name())
    then
        insert(Antwoord.NEE.name());
end

rule "Node 1 antwoord NEE voor node 3"
    when
        Node(id == 3,antwoord==Antwoord.NEE.name())
    then
        insert(Antwoord.NEE.name());
end
